from pathlib import Path
import re, shutil
r=Path('.')
shutil.copy2('../elya-firebase/google-services.json',r/'app/google-services.json')
# gradle
p=r/'build.gradle'; s=p.read_text()
if 'com.google.gms.google-services' not in s:s=s.replace("id 'com.android.application' version '8.7.3' apply false","id 'com.android.application' version '8.7.3' apply false\n    id 'com.google.gms.google-services' version '4.5.0' apply false")
p.write_text(s)
p=r/'app/build.gradle'; s=p.read_text()
if "id 'com.google.gms.google-services'" not in s:s=s.replace("id 'com.android.application'","id 'com.android.application'\n    id 'com.google.gms.google-services'",1)
s=re.sub(r'versionCode\s+4\b','versionCode 5',s,1);s=re.sub(r"versionName\s+'1\.0\.3'","versionName '1.0.4'",s,1)
if 'firebase-auth' not in s:s=s.replace('dependencies {',"dependencies {\n    implementation platform('com.google.firebase:firebase-bom:34.19.0')\n    implementation 'com.google.firebase:firebase-analytics'\n    implementation 'com.google.firebase:firebase-auth'\n    implementation 'com.google.firebase:firebase-firestore'",1)
p.write_text(s)
# java
p=r/'app/src/main/java/com/elya/music/MainActivity.java'; s=p.read_text()
if 'import com.google.firebase.auth.FirebaseAuth;' not in s:s=s.replace('import org.json.JSONArray;','''import com.google.firebase.auth.FirebaseAuth;\nimport com.google.firebase.auth.FirebaseUser;\nimport com.google.firebase.auth.UserProfileChangeRequest;\nimport com.google.firebase.firestore.FieldValue;\nimport com.google.firebase.firestore.FirebaseFirestore;\nimport com.google.firebase.firestore.SetOptions;\n\nimport org.json.JSONArray;''',1)
if 'private FirebaseAuth firebaseAuth;' not in s:s=s.replace('private final Map<String, MediaEntry> mediaMap = new HashMap<>();','private final Map<String, MediaEntry> mediaMap = new HashMap<>();\n    private FirebaseAuth firebaseAuth;\n    private FirebaseFirestore firestore;',1)
if 'firebaseAuth = FirebaseAuth.getInstance();' not in s:s=s.replace('webView = new WebView(this);','firebaseAuth = FirebaseAuth.getInstance();\n        firestore = FirebaseFirestore.getInstance();\n\n        webView = new WebView(this);',1)
bridge=r'''
        @JavascriptInterface public void firebaseCurrentUser(){FirebaseUser u=firebaseAuth.getCurrentUser();emitFirebaseState(u,null);if(u!=null)loadFirebaseProfile(u);}
        @JavascriptInterface public void firebaseEmailSignUp(String email,String password){String e=email==null?"":email.trim(),pw=password==null?"":password;if(e.isEmpty()||pw.length()<6){emitFirebaseError("Use a valid email and a password with at least 6 characters.");return;}firebaseAuth.createUserWithEmailAndPassword(e,pw).addOnSuccessListener(x->{FirebaseUser u=x.getUser();if(u==null)return;Map<String,Object>d=new HashMap<>();d.put("email",clean(u.getEmail()));d.put("displayName","Elya Listener");d.put("bio","");d.put("favoriteArtist","");d.put("createdAt",FieldValue.serverTimestamp());d.put("updatedAt",FieldValue.serverTimestamp());firestore.collection("users").document(u.getUid()).set(d,SetOptions.merge()).addOnCompleteListener(t->{emitFirebaseState(u,null);loadFirebaseProfile(u);emitFirebaseMessage("Elya account created.");});}).addOnFailureListener(e1->emitFirebaseError(firebaseFriendlyError(e1)));}
        @JavascriptInterface public void firebaseEmailSignIn(String email,String password){String e=email==null?"":email.trim(),pw=password==null?"":password;if(e.isEmpty()||pw.isEmpty()){emitFirebaseError("Enter your email and password.");return;}firebaseAuth.signInWithEmailAndPassword(e,pw).addOnSuccessListener(x->{FirebaseUser u=x.getUser();emitFirebaseState(u,null);if(u!=null)loadFirebaseProfile(u);emitFirebaseMessage("Signed in to Elya.");}).addOnFailureListener(e1->emitFirebaseError(firebaseFriendlyError(e1)));}
        @JavascriptInterface public void firebaseSignOut(){firebaseAuth.signOut();emitFirebaseState(null,null);emitFirebaseMessage("Signed out.");}
        @JavascriptInterface public void firebaseSaveProfile(String displayName,String bio,String favoriteArtist){FirebaseUser u=firebaseAuth.getCurrentUser();if(u==null){emitFirebaseError("Sign in to sync your profile.");return;}String n=displayName==null||displayName.trim().isEmpty()?"Elya Listener":displayName.trim(),b=bio==null?"":bio.trim(),f=favoriteArtist==null?"":favoriteArtist.trim();Map<String,Object>d=new HashMap<>();d.put("email",clean(u.getEmail()));d.put("displayName",n);d.put("bio",b);d.put("favoriteArtist",f);d.put("updatedAt",FieldValue.serverTimestamp());firestore.collection("users").document(u.getUid()).set(d,SetOptions.merge()).addOnSuccessListener(v->{u.updateProfile(new UserProfileChangeRequest.Builder().setDisplayName(n).build());emitFirebaseMessage("Profile synced to Elya Cloud.");loadFirebaseProfile(u);}).addOnFailureListener(e1->emitFirebaseError(firebaseFriendlyError(e1)));}
'''
if 'firebaseEmailSignIn' not in s:
    a='\n    private class ElyaChromeClient extends WebChromeClient {';i=s.index(a);j=s[:i].rfind('\n    }');s=s[:j]+bridge+s[j:]
helpers=r'''
    private void emitFirebaseState(FirebaseUser u,JSONObject profile){try{JSONObject o=new JSONObject();o.put("signedIn",u!=null);if(u!=null){o.put("uid",u.getUid());o.put("email",clean(u.getEmail()));o.put("displayName",clean(u.getDisplayName()));}if(profile!=null)o.put("profile",profile);js("window.__elyaFirebaseAuthState&&window.__elyaFirebaseAuthState("+o.toString()+");");}catch(Exception ignored){}}
    private void loadFirebaseProfile(FirebaseUser u){if(u==null)return;firestore.collection("users").document(u.getUid()).get().addOnSuccessListener(d->{try{JSONObject p=new JSONObject();p.put("displayName",clean(d.getString("displayName")));p.put("bio",clean(d.getString("bio")));p.put("favoriteArtist",clean(d.getString("favoriteArtist")));emitFirebaseState(u,p);}catch(Exception e){emitFirebaseState(u,null);}}).addOnFailureListener(e->emitFirebaseState(u,null));}
    private void emitFirebaseError(String m){js("window.__elyaFirebaseError&&window.__elyaFirebaseError("+JSONObject.quote(m==null?"Firebase error":m)+");");}
    private void emitFirebaseMessage(String m){js("window.__elyaFirebaseMessage&&window.__elyaFirebaseMessage("+JSONObject.quote(m==null?"Done":m)+");");}
    private static String firebaseFriendlyError(Exception e){String m=e==null||e.getMessage()==null?"Could not complete the account action.":e.getMessage();return m.length()>180?m.substring(0,180):m;}
'''
if 'private void emitFirebaseState(' not in s:s=s.replace('\n    private String queryName(Uri uri) {','\n'+helpers+'\n    private String queryName(Uri uri) {',1)
p.write_text(s)
# html UI
p=r/'app/src/main/assets/index.html'; h=p.read_text()
css='''<style id="elyaFirebase104Style">.elya-account{margin:4px 0 18px;padding:15px;border:1px solid rgba(var(--accent-rgb),.18);border-radius:18px;background:rgba(var(--accent-rgb),.045)}.elya-account-head{display:flex;align-items:center;gap:10px;margin-bottom:12px}.elya-account-head svg{width:20px;height:20px;color:var(--accent)}.elya-account-head small{color:var(--muted)}.elya-auth-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.elya-auth-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.elya-auth-actions button{flex:1}.elya-auth-status{font-size:11px;color:var(--muted);margin-top:9px}.elya-cloud{display:none}.elya-account.signed .elya-login{display:none}.elya-account.signed .elya-cloud{display:block}.elya-cloud-id{padding:10px 12px;border:1px solid var(--line);border-radius:13px;margin-bottom:10px}.elya-cloud-id strong,.elya-cloud-id small{display:block}.elya-cloud-id small{color:var(--muted);margin-top:2px}@media(max-width:700px){.elya-auth-grid{grid-template-columns:1fr}}</style>'''
if 'elyaFirebase104Style' not in h:h=h.replace('</head>',css+'</head>',1)
block='''<div class="elya-account" id="elyaAccount"><div class="elya-account-head"><svg><use href="#i-user"/></svg><div><strong>Elya Account</strong><br><small>Optional cloud profile. Music stays local.</small></div></div><div class="elya-login"><div class="elya-auth-grid"><div class="field"><label>Email</label><input id="elyaAuthEmail" type="email" placeholder="name@example.com"></div><div class="field"><label>Password</label><input id="elyaAuthPassword" type="password" placeholder="6+ characters"></div></div><div class="elya-auth-actions"><button class="primary" id="elyaSignIn">Sign In</button><button class="secondary" id="elyaCreate">Create Account</button></div><div class="elya-auth-actions"><button class="secondary" disabled>Google · setup pending</button><button class="secondary" disabled>Phone · setup pending</button></div><div class="elya-auth-status" id="elyaAuthStatus">Sign in only if you want cloud features.</div></div><div class="elya-cloud"><div class="elya-cloud-id"><strong id="elyaCloudName">Elya Listener</strong><small id="elyaCloudEmail"></small></div><div class="field"><label>Bio</label><input id="elyaCloudBio" maxlength="140" placeholder="A short bio"></div><div class="elya-auth-actions"><button class="danger-btn" id="elyaSignOut">Sign Out</button></div><div class="elya-auth-status" id="elyaCloudStatus">Profile sync is on.</div></div></div>'''
if 'id="elyaAccount"' not in h:
    a='<div class="modal" id="profileModal"><div class="dialog">\n  <div class="dialog-head"><h3>User Profile</h3><button class="close" data-close="profileModal"><svg><use href="#i-close"/></svg></button></div>'
    if a not in h:raise SystemExit('profile anchor missing')
    h=h.replace(a,a+'\n'+block,1)
js=r'''<script id="elyaFirebase104Script">(()=>{const q=s=>document.querySelector(s),B=()=>window.AndroidMusic;let C={signedIn:false};function st(t){const x=q(C.signedIn?'#elyaCloudStatus':'#elyaAuthStatus');if(x)x.textContent=t||''}function draw(d){C=d||{signedIn:false};q('#elyaAccount')?.classList.toggle('signed',!!C.signedIn);if(!C.signedIn)return;const p=C.profile||{};if(q('#elyaCloudName'))q('#elyaCloudName').textContent=p.displayName||C.displayName||'Elya Listener';if(q('#elyaCloudEmail'))q('#elyaCloudEmail').textContent=C.email||'';if(q('#elyaCloudBio'))q('#elyaCloudBio').value=p.bio||''}window.__elyaFirebaseAuthState=d=>{draw(d);st(d?.signedIn?'Connected to Elya Cloud.':'Sign in only if you want cloud features.')};window.__elyaFirebaseError=m=>{st(m);window.toast?.(m)};window.__elyaFirebaseMessage=m=>{st(m);window.toast?.(m)};q('#elyaSignIn')?.addEventListener('click',()=>B()?.firebaseEmailSignIn?.(q('#elyaAuthEmail')?.value||'',q('#elyaAuthPassword')?.value||''));q('#elyaCreate')?.addEventListener('click',()=>B()?.firebaseEmailSignUp?.(q('#elyaAuthEmail')?.value||'',q('#elyaAuthPassword')?.value||''));q('#elyaSignOut')?.addEventListener('click',()=>B()?.firebaseSignOut?.());const old=q('#saveProfile')?.onclick;if(q('#saveProfile'))q('#saveProfile').onclick=function(e){old?.call(this,e);if(C.signedIn)B()?.firebaseSaveProfile?.(q('#profileName')?.value||'Elya Listener',q('#elyaCloudBio')?.value||'',q('#profileArtist')?.value||'')};q('#profileBtn')?.addEventListener('click',()=>setTimeout(()=>B()?.firebaseCurrentUser?.(),80));setTimeout(()=>B()?.firebaseCurrentUser?.(),900)})();</script>'''
if 'elyaFirebase104Script' not in h:h=h.replace('</body>',js+'</body>',1)
p.write_text(h)
print('Elya 1.0.4 Firebase accounts applied')
